src/Commands/InstallCommand.php

When executing the native:install command, the default nativephp.php configuration file was not published to the config folder.

Fix install command

---

src/Commands/DevelopCommand.php

This PR fixes the **TTY mode is not supported on Windows platform.** error.

Fix the issue of starting the development server

---

resources/js/package.json

Windows 10 and 11 will sometimes open the electron-builder.js file in the default application during native:install or native:serve this ensure it's processed correctly.
I confirmed it has no impact on Mac.
It also needs either #47 or #52 to fully resolve Windows builds.

Resolve Windows opening config file in default application

---

src/Commands/PublishCommand.php

The target OS is set in the `electron-builder.js` file. Having it hard coded here is redundant / leads to a non existent path

Correct NATIVEPHP_PHP_BINARY_PATH

---

src/Commands/QueueWorkerCommand.php

Fix php path in queue command. It is pointing to the directory, not the php binary

Fix php path in queue command

---

resources/js/electron-builder.js

To begin with, thank you so much for your hard work. This is an a fantasticep for the PHP community!
This is not meant to be the final solution, but it solves the problem pointed out at this issue: https://github.com/NativePHP/electron/issues/55
After briefly checking the code, I cou't find any place to trigger the npm post-installation to have the option `--linux`. Due to that, an extra check for the platform was needed for the initial script to copy the binary from Linux folder. 
The same fix might be needed for Windows.

Linux extra condition for electron builder.

---

resources/js/electron-builder.js

Without this condition, when we run "php artisan native:serve" on a Windows OS, it copies the PHP binary from the Mac folder instead of the Windows folder. This occurs because the "isWindows" condition is false, and we never receive a "--win" argument in the "process.argv" array when serving the app. Comparing "win32" from the "os.platform()" method fixes this issue.

windows extra condition for electron builder.

---

src/Commands/BuildCommand.php
src/Commands/InstallCommand.php
src/Commands/PublishCommand.php
src/Traits/ExecuteCommand.php
src/Traits/Installer.php

Currently, we're unable to compile a NativePHP application in a CI environment (ie GitHub Actions) because dev/tty is not writable.
This change introduces a new `--ci` flag to the following commands:
- native:install
- native:build
- native:publish
This fixes https://github.com/NativePHP/laravel/issues/179 and allows compiling in a CI environment

Allow compiling packages in a CI environment

---

tests/ExampleTest.php

Process was undefined because it was not imported.
```php
try {
retry(12, function () {
// Wait until port 8100 is open
dump('Waiting for port 8100 to open...');
$fp = @fsockopen('localhost', 8100, $errno, $errstr, 1);
if ($fp === false) {
throw new Exception('Port 8100 is not open yet');
}
}, 5000);
} catch (Exception $e) {
Process::run('pkill -9 -P '.$process->id()); //Undefined
throw $e;
}
Process::run('pkill -9 -P '.$process->id()); //Undefined
```
But used here : 
```php
$process = \Illuminate\Support\Facades\Process::path(base_path())
```

Fix undefined class Process in ExampleTest.php

---

resources/js/package.json

Adding a space between "cross-env" and "node" resolved the error that was occurring when running "php artisan native:build mac" without spaces.

add space between cross-env and node

---

src/Commands/PublishCommand.php

I was trying to run the `native:publish` command when I encountered the following error:
```
In PublishCommand.php line 34:
Call to undefined function Native\Electron\Commands\select()
```
So I imported the right function from Laravel Prompts to make it work.

Fixed missing import of select() function from Laravel Prompts

---

resources/js/php.js

Fix regression from:
https://github.com/NativePHP/electron/commit/ab99e94ed49b27e5b5cd16f8668fcad882611d47

fix: add missing platform.arch for Linux and Windows

---

src/Commands/BuildCommand.php
src/Commands/DevelopCommand.php
src/Traits/InstallsAppIcon.php

Replaces #72 with a simpler "just put the file in the right place" approach.
Simply put your icon in `public/icon.png` and it will be moved into the right place for Electron to do its thing.

App Icon version 2

---

resources/js/electron-builder.js
src/Commands/BuildCommand.php

This PR respects the deeplink scheme as set in `.env` / `config/nativephp.php`

Customizable deeplink scheme

---

src/Concerns/LocatesPhpBinary.php

Noticed that the php-bin binary path is hardcoded. This isn't great if people need to compile their own versions for needing specific extensions like Zip or Xml. This allows users to set an environment variable to overwrite that.

Add environment variable for php bin directory.

---

src/Commands/DevelopCommand.php
src/Traits/Developer.php
src/Traits/ExecuteCommand.php

This will allow us to run the command shelled through another command, which allows for a concurrent command like Laravel's new `composer dev` command, i.e. adding this to the `scripts` section of your `composer.json`:
```json
"scripts": {
"native:dev": [
"Composer\\Config::disableProcessTimeout",
"npx concurrently -c \"#93c5fd,#c4b5fd,#fb7185\" \"php artisan native:serve --no-interaction\" \"php artisan pail --timeout=0\" \"npm run dev\" --names=app,logs,vite"
]
},
```
Then you can run `composer native:dev` and get your app booted in dev mode, watch the logs with Pail (requires installation), and be running Vite for hot reloading 🔥

Support `--no-interaction` in `native:serve` command

---

resources/js/electron-plugin/dist/server/api/window.js
resources/js/electron-plugin/src/server/api/window.ts
resources/js/package-lock.json
resources/js/yarn.lock

Electron support for https://github.com/NativePHP/laravel/pull/391

Improved window management

---

resources/js/electron-plugin/src/server/api/notification.ts

Resubmission of https://github.com/NativePHP/electron-plugin/pull/4

Add support for custom events fired by clicking on notifications

---

resources/js/electron-builder.js

In windows, `php` is getting resolved as `C:\Users\virtualbox\Downloads\laravel\api\vendor\nativephp\electron\\resources\js\php.js` instead of system `php.exe`.
`> where php` results in 2 php executables `php.js` and `php.exe` relative to `resources/js/electron-builder.js`. This is causing a fail in the windows build during `php artisan native:minify` step 
- https://github.com/NativePHP/laravel/issues/338

Fix windows php path for native:minify

---

resources/js/electron-plugin/dist/server/api/notification.js
resources/js/electron-plugin/dist/server/php.js
resources/js/electron-plugin/src/server/php.ts
resources/js/yarn.lock

Explicitly render exceptions reported via the `php -S`'s `STDERR` so that they are visible to the developer when running debug builds.
Requires https://github.com/NativePHP/laravel/pull/398

Add PHP server exception reporting

---

resources/js/electron-plugin/src/server/api/menuBar.ts

Currently, MenuBar windows are limited in what they're capable of:
- Some settings can't be changed once they've been created, such as the [icon](https://github.com/orgs/NativePHP/discussions/142).
- The window itself doesn't have the same controls as other windows (e.g. they are always user-resizable and [can't be made a fixed size](https://github.com/orgs/NativePHP/discussions/159)).
- Some features aren't exposed, such as tooltip text.
- The window doesn't receive any events from Electron or Laravel, making it impossible to use our Native events in JS or Livewire.
- Context menus or MenuBar windows are the only option, there's no support for [custom logic](https://github.com/orgs/NativePHP/discussions/246).
This PR aims to fix all of these issues. It also defaults to preloading the …

MenuBar improvements

---

resources/js/electron-plugin/src/server/api/menuBar.ts

Some quirks that this fixes:
- When using `showDockIcon` and not `onlyShowContextMenu`, if you click the dock icon, the menu bar will activate _even if your app has other windows that will show_
- This event also duplicates the icon on Mac (really recreating the MenuBar)
- If you do set `onlyShowContextMenu`, we stopped sending the right-click event to Laravel

Fix some MenuBar quirks

---

resources/js/electron-plugin/src/server/api/dock.ts
resources/js/electron-plugin/src/server/state.ts

Adds support for:
- Bouncing the Dock icon
- Setting the badge value
- Changing the icon
- Toggling icon visibility

Dock goodies

---

resources/js/electron-plugin/src/server/api/menuBar.ts

- Allow future calls to the menu bar to recreate it
- Support more events in a standard way
- Hide the popover when right-clicking to show the context menu

MenuBars continued

---

resources/js/electron-plugin/src/server/api/powerMonitor.ts

Several fixes and improvements (with https://github.com/NativePHP/laravel/pull/445)
-  [x] Add events for `lock-screen`, `unlock-screen`, `shutdown`, `user-did-become-active`, and `user-did-resign-active` as they are useful for checking the IdleState without constantly polling
-  [x] Add a testing mock
----- 
The power monitor facade is really useful, especially for our battery-powered computers. 
It just needs some refinement, which is the purpose of this PR.
Here is an example usage:

Fixes and improvements to powerMonitor

---

resources/js/electron-plugin/src/server/api/window.ts
resources/js/electron-plugin/tests/endpoints/window.test.ts

This PR adds support for showing windows (I'll open the necessary PR in the NativePHP/laravel repo soon). I tried adding tests to match the dialog and clipboard tests, but I couldn't figure out why I was getting an error when I tried asserting a method was called.
Here's the error in case you have suggestions you'd like me to try:
```sh
FAIL  electron-plugin/tests/endpoints/window.test.ts
● Test suite failed to run
electron-plugin/tests/endpoints/window.test.ts:36:21 - error TS2339: Property 'window' does not exist on type 'typeof CrossProcessExports'.
36     expect(electron.window.show).toHaveBeenCalled();
```

Add support for window.show()

---

resources/js/electron-plugin/dist/server/api/menuBar.js
resources/js/electron-plugin/dist/server/state.js
resources/js/electron-plugin/src/server/api/menuBar.ts
resources/js/electron-plugin/src/server/state.ts

Creating a context menu only tray is now fully independent of menubar plugin.

fix: menubar tray state

---

resources/js/electron-plugin/dist/index.js
resources/js/electron-plugin/src/index.ts

For unknown reasons, PHP server child processes will persists when closing NativePHP app `CMD+Q`
It doesn't happens when using `CTRL+C` on `php artisan native:serve`. 
The only difference I see is that `CTRL+C` send an `SIGINT`, instead of a graceful `SIGTERM`.
From my research: 
- `SIGINT` for **immediate** interruption (user-driven).
- `SIGTERM` for a **graceful** termination (programmatic request).

fix: kill tree php server

---

.github/workflows/run-tests.yml
composer.json
src/Commands/BuildCommand.php

Fixes https://github.com/NativePHP/laravel/issues/468
- Utilises the Symfony Process class which has a tried and tested `isTtySupported()` method. This will return false if windows due to a DIRECTORY_SEPARATOR check.
- Removed check for Windows specifically as this is checked as above.
- Ensures even if TTY is supported, it is still set to off when -n|--non-interactive is specified.
https://symfony.com/doc/current/components/process.html#checking-for-tty-support

Update logic to ensure TTY mode is appropriately disabled

---

composer.json

update nativephp/laravel version constraint to allow all versions during development

fix: update nativephp/laravel version constraint

---

resources/js/electron-plugin/src/server/api/notification.ts

- Added a reference to the notifications so that you can identify which notification was clicked.
- Implemented more events for notifications: reply, action, and close.
---
Goes hand in hand with https://github.com/NativePHP/laravel/pull/498

Expand notification api with reference and more events

---

.github/workflows/fix-php-code-style-issues.yml

Since main is now protected, this workflow ceased to function.
Proposing an alternative where it only check linting error on main and fix them on pull requests
Same as https://github.com/NativePHP/laravel/pull/499

fix: linting workflow

---

src/Traits/PrunesVendorDirectory.php

Fixes https://github.com/NativePHP/laravel/issues/503
- Ensure php-bin is removed after composer has run
- Resolves notarisation issues with apple
- Reduces app size

Ensure php-bin is removed from built app

---

src/Traits/CopiesToBuildDirectory.php

We ran into an issue while building, caused by a linked storage directory.
This works as expected on mac, but failed on windows. Symlinks do not really exist there, thus the existing conditional clauses had some unexpected behaviour.
Using symlinks is discouraged as per the docs: https://nativephp.com/docs/desktop/1/digging-deeper/files#symlinks
Pete and I had a quick call, and decided to skip (but log) whenever a copy error occurred. 
We might need to harden this further

Skip errors when copying files during build

---

resources/js/php.js
src/Commands/BuildCommand.php
src/Commands/DevelopCommand.php
src/Traits/CopiesCertificateAuthority.php
src/Traits/ExecuteCommand.php
tests/Unit/Traits/CopiesCertificateAuthorityTest.php

This pull request includes several changes to improve the handling of the CA certificate in the `Native\Electron` package. The most important changes involve the introduction of a new trait for copying the CA certificate and the removal of redundant code related to certificate handling.
* [`src/Traits/CopiesCertificateAuthority.php`](diffhunk://#diff-900fb9b99b5b364427987e22c8819c25cc1594ac36bcae1d320ecf8bd0cec119R1-R47): Added a new trait `CopiesCertificateAuthority` to encapsulate the logic for copying the CA certificate.
* [`src/Commands/BuildCommand.php`](diffhunk://#diff-aa5dd2724f30cebdd7795cf02ae6a572645fd33f0048b4cb27f37fdc985a46b0R10): Updated the `BuildCommand` class to use the new `CopiesCertificateAuthority` trait and removed the old certificate copying logic. …

Basic Build Command cleanup

---

resources/js/electron-plugin/src/server/api.ts
resources/js/electron-plugin/src/server/api/alert.ts
resources/js/electron-plugin/src/server/api/dialog.ts
resources/js/electron-plugin/tests/endpoints/alert.test.ts
resources/js/electron-plugin/tests/endpoints/dialog.test.ts

I saw that there were remnants of the Electron-MessageBox Api. I removed the remnants from the dialog and created a new class “Alert”.
PR: NativePHP/laravel
https://github.com/NativePHP/laravel/pull/523

Add alert API routes and corresponding tests

---

src/Commands/PublishCommand.php

This PR adds the `all` option to the `publish` command. Making it symmetrical to the `build` command

add 'all' option to `publish` command

---

resources/js/electron-plugin/dist/server/api/menuBar.js
resources/js/electron-plugin/src/server/api/menuBar.ts

The menubar tray can be null with window content
No tray is set in the options:
Null for tray is possible:
Noticed by error message in the console:

Fix menubar tray can be nullable

---

resources/js/electron-builder.js
src/Commands/BuildCommand.php

PR:
NativePHP/laravel: https://github.com/NativePHP/laravel/pull/534
NativePHP/nativephp.com: https://github.com/NativePHP/nativephp.com/pull/100

Add copyright information to build configuration

---

src/Commands/BundleCommand.php

The ZIP extension in PHP expects forward slashes (/) as directory separators inside archives, regardless of the operating system.

fix: zephpyr.com bundle on Windows

---

src/Commands/BuildCommand.php

This pull request includes a change to the `src/Commands/BuildCommand.php` file. The change adds new environment variables related to notarization to the `getEnvironmentVariables` method.
Notarization-related changes:
* [`src/Commands/BuildCommand.php`](diffhunk://#diff-aa5dd2724f30cebdd7795cf02ae6a572645fd33f0048b4cb27f37fdc985a46b0R149-R152): Added `NATIVEPHP_APPLE_ID`, `NATIVEPHP_APPLE_ID_PASS`, and `NATIVEPHP_APPLE_TEAM_ID` environment variables to support notarization.

Ensure notarization env vars are available even if config is cached

---

src/Commands/ResetCommand.php

`__DIR__.'/../../resources/js/resources/app/`
directory does not exist the first time.

fix: ensure native serve resource path is cleared only if it exists

---

.github/workflows/run-tests.yml

This pull request includes a change to the GitHub Actions workflow configuration to update the test matrix for Laravel versions.
Changes in `.github/workflows/run-tests.yml`:
* Removed support for Laravel 10.x from the test matrix.
* Removed the exclusion rule for Laravel 10.x and PHP 8.4, as Laravel 10.x is no longer included in the matrix.

Remove L10 from test matrix

---

.github/workflows/build-plugin.yml
.github/workflows/run-plugin-tests.yml
.github/workflows/run-tests.yml
resources/js/package-lock.json
resources/js/package.json
resources/js/yarn.lock

This pull request includes updates to the Node.js version used in various workflows and configuration files. The most important changes are:
* [`.github/workflows/build-plugin.yml`](diffhunk://#diff-44260e475d64853240418a679115f63b0361b0fb3146feb63aaffc1c8e03c253L26-R26): Updated Node.js version from 20.x to 22.x.
* [`.github/workflows/run-plugin-tests.yml`](diffhunk://#diff-c903a184c2dc100024b6e3bf6dc77a9774207c7bf4e8f1877db9d2e2ae2a75bbL17-R17): Updated Node.js version from 20.x to 22.x.
* [`.github/workflows/run-tests.yml`](diffhunk://#diff-7314d0ebbd2e9537ae4889316745b4fd2fa43cb86275c9caae18a86ba228b642L36-R36): Updated Node.js version from 20.x to 22.x.
* [`resources/js/package-lock.json`](diffhunk://#diff-478553ce7a4d6ba114bb49cbb02b69562f8f3dda644dfa3296f60983b676d070L76-R76): …

Node Minimum Version Bump to Support Electron

---

src/Commands/BundleCommand.php
src/Traits/PrunesVendorDirectory.php

This bug bundled every PHP version when custom PHP binaries were used, resulting in a large Electron file and blocking the notarization process.
- Increased timeout for composer install  
- Clean up custom PHP binary package directory

fix: custom PHP binary package not pruned on build

---

src/Traits/CleansEnvFile.php

The goal is to not have "info" logs of nativePHP/Electron javascript events.

fix: set LOG_LEVEL to "warning" in production

---

resources/js/electron-plugin/dist/server/php.js
resources/js/electron-plugin/src/server/php.ts

With the added environment variable in this [commit](https://github.com/NativePHP/electron/commit/a2f98889a18d00a5b9e9342f06d51b6c6bf09db6#diff-edf9ec79371541b54bd5647c93b0ba374e50d9986b59c2acd57f410d70d8bb8bR140), we definitely need to create those directories ourselves.
**Why did it work before?**  
Because previously, the app was sometimes writing to itself.  
With bundling, we need every write operation to be outside the app.  
This is why we introduced the usage of `LARAVEL_STORAGE_PATH`.

fix: Please provide a valid cache path.

---

resources/js/electron-plugin/dist/index.js
resources/js/electron-plugin/src/index.ts

Fixes: https://github.com/NativePHP/laravel/issues/542
Getting a Bad File Descriptor Error after the app is resumed from sleep for every scheduler run.
Laravel scheduler improvement:
* Imported `powerMonitor` module from `electron`
* Added event listeners for `suspend` and `resume` events to manage scheduler state
* Introduced a `stopScheduler` method to clear and reset the scheduler interval

fix: handle power monitor events to manage scheduler lifecycle

---

src/Commands/BuildCommand.php
src/Commands/BundleCommand.php
src/Commands/DevelopCommand.php
src/Commands/ResetCommand.php
src/Traits/PatchesPackagesJson.php

From electron code comment:
> getVersion(): string; The version of the loaded application. If no version is found in the application's package.json file, the version of the current bundle or executable is returned.

fix: App::version() not returning the correct version

---

src/Traits/PatchesPackagesJson.php

Added fields `description`, `author`, and `homepage` to the package.json patching logic, sourced from configuration values. This ensures more comprehensive metadata is included when generating or updating the package.json file.
PR:
NativePHP/laravel: https://github.com/NativePHP/laravel/pull/571

Update package.json patch logic to include new fields

---

resources/js/electron-plugin/dist/server/api/app.js
resources/js/electron-plugin/src/server/api/app.ts

Added a new `/relaunch` POST endpoint to restart the app with relaunch options. It uses `app.relaunch` with the current arguments and then quits the app. This ensures a seamless restart process for the application.
PR:
NativePHP/laravel: https://github.com/NativePHP/laravel/pull/569

Add endpoint to relaunch the app

---

resources/js/electron-plugin/dist/server/api/menuBar.js
resources/js/electron-plugin/src/server/api/menuBar.ts

Integrate the `showOnAllWorkspaces` parameter into menuBar API logic, allowing greater control over workspace visibility. Defaults are applied to ensure backward compatibility when the parameter is not provided.
PR:
NativePHP/laravel: https://github.com/NativePHP/laravel/pull/568

Add support for `showOnAllWorkspaces` parameter in menuBar

---

src/Traits/InstallsAppIcon.php

Extended the InstallsAppIcon trait to copy .ico and .icns icon formats alongside existing ones. This ensures compatibility with platforms requiring these formats.
For macOS: icon.icns
For Windows: icon.ico
Fallback: icon.png
Doc PR: https://github.com/NativePHP/nativephp.com/pull/119

Add support for additional app icon formats

---

src/Commands/BundleCommand.php
src/Traits/CopiesToBuildDirectory.php

This pull request updates the file exclusion lists in two parts of the codebase to include the `auth.json` file, which potentially contains sensitive information. This ensures that the file is excluded during bundling and copying operations.
* [`src/Commands/BundleCommand.php`](diffhunk://#diff-9b3b84dab5d391dcf768c3ff5fc1a0edce75dfcc487379e6af7a5a7a3da200deR239): Added `auth.json` to the list of files excluded from the zip archive during the bundling process.
* [`src/Traits/CopiesToBuildDirectory.php`](diffhunk://#diff-3b7ec76d21b431dbdf1173367a4e905b01bb7e3d00675d99b3f2bff89397f8a1R37): Added `auth.json` to the list of files excluded from being copied to the build directory.

Add extra sensitive files to cleanup

---

resources/js/electron-plugin/dist/server/api/window.js
resources/js/electron-plugin/src/server/api/window.ts

Updated the logic to set window width and height to ignore stored window state when `resizable` is false. This ensures consistent behavior for fixed-size windows regardless of previous state data.

Adjust window dimensions based on the `resizable` property.

---

src/Traits/CopiesToBuildDirectory.php

Sometimes some files are considered folders (or are hidden files) and the are unable to be copied on Windows.
Showing which causes the exception to be thrown makes easy to investigate on the issue.

Added file to warning message relative to the copy() call

---

resources/js/electron-plugin/dist/server/state.js
resources/js/electron-plugin/src/server/state.ts

Fix: Account for all changed keys in settingsStore.onDidAnyChange
This commit addresses an issue where only the *first* changed key was being processed when multiple settings were updated simultaneously. The previous implementation used `Object.keys(newValue).find()` which stops after finding the first difference.
The updated code now iterates through *all* keys in the `newValue` object and compares them to their corresponding values in `oldValue`. This ensures that every changed setting triggers the `notifyLaravel` function, providing a complete and accurate representation of settings modifications.
Specifically, this change is crucial in scenarios where:
*   `clear()` or `reset()` are called on the settings store.
*   Multiple settings are updated within a single operation.
*   The …

fix: take into account all changed keys

---

.github/workflows/build-plugin.yml
resources/js/electron-plugin/dist/server/php.js
resources/js/electron-plugin/src/server/php.ts

Symlinks have been discouraged as per the docs for some time.
We still ran `storage:link` under the hood. The command is invoked in a separate process, thus did not prevent the app from working. But it did fill up the logs as reported by some users https://github.com/NativePHP/laravel/issues/601
This PR removes it.
@simonhamp Do you want this mentioned in the docs explicitly?

remove storage:link

---

resources/js/build/notarize.js

The after sign hook was only checking if the process was running on a Mac, but didn't take the build target into account. 
This pull request adds a small guard clause to the `notarize.js` file to ensure notarization only occurs for macOS builds.
Fixes: https://github.com/NativePHP/laravel/issues/653

Only trigger notarization hook on Mac build target

---

src/Traits/CopiesCertificateAuthority.php

When using custom PHP binaries the `CopiesCertificateAuthority` trait would look for the `cacert.pem` file relative to the custom binary path. 
It's not documented that users should provider their own certificate bundle in this case. I see no reason why we should not use the default certs used by `php-bin`. Since we include the repo by default it should always be there & be updated.
This PR removes the conditional & makes sure the certs in `vendor/nativephp/php-bin/cacert.pem` are always used.
Fixes: https://github.com/NativePHP/laravel/issues/655

use vendor cacert.pem for custom binaries

---

resources/js/electron-plugin/dist/index.js
resources/js/electron-plugin/src/index.ts

Deeplink handling on Windows was passing a `workingDirectory` parameter to the `OpenedFromURL` event.
This was causing issues when opening deep-links on Windows
Fixes: https://github.com/NativePHP/laravel/issues/599

remove workingDirectory from Windows deep-link handler

---

resources/js/electron-plugin/dist/server/api/window.js
resources/js/electron-plugin/src/server/api/window.ts

Enhanced the window API by including support for the `skipTaskbar` and `hiddenInMissionControl` properties, enabling more control over window visibility and behavior.
PR
NativePHP/laravel: https://github.com/NativePHP/laravel/pull/671

Add `skipTaskbar` and `hiddenInMissionControl` properties to window API

---

resources/js/electron-plugin/dist/index.js
resources/js/electron-plugin/dist/server/index.js
resources/js/electron-plugin/src/index.ts
resources/js/electron-plugin/src/server/api/childProcess.ts
resources/js/electron-plugin/src/server/index.ts

This PR ensures that only one scheduler process runs at a time and that it is properly terminated when needed. The changes add functionality to explicitly kill the scheduler process, preventing potential orphaned processes
Potentially related: https://github.com/NativePHP/laravel/issues/542

cleanup stray scheduler processes

---

resources/js/electron-plugin/dist/server/api/window.js
resources/js/electron-plugin/src/server/api/window.ts

**This PR allows developers to disable the opening of potentially unwanted pop-up windows.**
By default, Electron doesn't prevent sub-windows to be opened out of a window. This would for instance be the case if a user middle-clicks a link. This behaviour is potentially undesirable in a desktop application, as it enables the user to "break out" of a window.
To prevent additional windows from opening, this PR adds a `suppressNewWindows()` method that can be applied when opening a new window. It will prevent any pop-up windows being opened.
_Laravel PR:_ https://github.com/NativePHP/laravel/pull/685
_Docs PR:_ https://github.com/NativePHP/nativephp.com/pull/200
If there's anything you'd like me to tweak or improve in this PR, please let me know. 😊

Allow optional suppression of opening sub-windows
