- README.md
> fix: README badges

- composer.json
> composer package local path remove for production release #14

- src/Commands/DevelopCommand.php
Hello,
I've removed yarn dependency from native:serve command.
> Remove yarn dependency when using serve command

- src/Concerns/LocatesPhpBinary.php
Hi, following from https://github.com/NativePHP/php-bin/pull/6 I changed the binary lookup to include Linux-based platform!
> Added binary lookup for linux based platform

- src/Commands/BuildCommand.php
> Fix native:build npm timeout

- resources/js/package.json
> fix(linux build commands): add missing 'x64' flag

- src/Updater/GitHubProvider.php
- src/Updater/UpdaterManager.php
This PR allows users to publish their compiled application to GitHub Releases.
I'll raise a separate PR in the NativePHP/laravel package to update the nativephp.php config stub and another for the docs
> Upload to GitHub Releases

- src/Commands/PublishCommand.php
From [Discord thread](https://discord.com/channels/1136045642154790955/1138340354219851797/1236944150268481616)
> Fix publish command

- resources/js/electron-builder.js
Fixes https://github.com/NativePHP/laravel/issues/206
> Remove forced config from Electron config

- .github/workflows/run-tests.yml
- composer.json
- src/Commands/DevelopCommand.php
- src/Traits/Developer.php
- tests/ExampleTest.php
- tests/TestCase.php
There were several issue:
- TTY issues due to it not using `--no-interaction`
- Linux required setting up X11 (Xvfb is already installed)
I also cleaned up the only existing Test.
We got to have that little green badge. The workflows passed on my fork.
> Fixed Tests

- composer.json
> Fix for Laravel Prompts version

- resources/js/electron-plugin/dist/server/api/window.js
- resources/js/electron-plugin/src/server/api/window.ts
In order to accommodate the [feature](https://github.com/orgs/NativePHP/discussions/371) for listing all windows I created this MR.
> Add endpoint for listing all windows

- resources/js/electron-plugin/dist/server/php.js
- resources/js/electron-plugin/src/server/php.ts
See issue: https://github.com/NativePHP/laravel/issues/399#issuecomment-2466845326
> [BUG] Change the relative path to the application in order to line up

- resources/js/electron-plugin/dist/server/api/powerMonitor.js
- resources/js/electron-plugin/src/server/api/powerMonitor.ts
Fixes https://github.com/NativePHP/laravel/issues/383
> Fix powerMonitor events

- resources/js/electron-plugin/src/server/childProcess.ts
As the title describes. Related to https://github.com/NativePHP/laravel/pull/402
> Tidy / remove commented out child process env merge

- resources/js/package.json
Fixes https://github.com/NativePHP/laravel/issues/418
> Fix script identity

- resources/js/electron-plugin/src/server/api/settings.ts
- added an endpoint to clear settings
Goes with https://github.com/NativePHP/laravel/pull/432
> feat: add clear endpoint to settings

- resources/js/electron-plugin/dist/index.js
- resources/js/electron-plugin/dist/server/index.js
- resources/js/electron-plugin/dist/server/php.js
- resources/js/electron-plugin/src/index.ts
- resources/js/electron-plugin/src/server/index.ts
- resources/js/electron-plugin/src/server/php.ts
Modifications related to https://github.com/NativePHP/laravel/pull/450. Should be released together.
> Remove queue worker initialization

- resources/js/electron-plugin/src/server/api/system.ts
Avoid zombies when printing in silent mode
> close print window before freeing mem

- resources/js/electron-plugin/dist/server/api/menuBar.js
- resources/js/electron-plugin/src/server/api/menuBar.ts
See https://github.com/NativePHP/laravel/pull/453
> Fix menubar not ready

- composer.json
Fixes https://github.com/NativePHP/laravel/issues/477
> Ensure 1.0.0-beta.1 or higher is required in v1 for laravel package

- resources/js/electron-plugin/src/server/api/app.ts
This PR adds the route to exit the application. The customization of the nativephp/laravel project was also done.
https://github.com/NativePHP/laravel/pull/519
> Add route to quit the application

- resources/js/electron-plugin/dist/server/api/alert.js
- resources/js/electron-plugin/src/server/api/alert.ts
PR:
NativePHP/laravel: https://github.com/NativePHP/laravel/pull/529
> fix: alert - handling of null values

- src/Commands/BundleCommand.php
Some apps just doesn't have css. Weird right?
> Fix: bundle apps without frontend assets

- resources/js/electron-plugin/dist/server/api/autoUpdater.js
- resources/js/electron-plugin/src/server/api/autoUpdater.ts
- resources/js/package-lock.json
- resources/js/yarn.lock
Fixed auto updater import and updated dependencies.
----
I have several personal development tools written in native PHP that I run locally always with the latest development version of both Laravel and the Electron package. This led me to discover this runtime error.
> fix: autoupdater import

- resources/js/electron-plugin/dist/server/api/app.js
- resources/js/electron-plugin/src/server/api/app.ts
PR:
NativePHP/laravel: https://github.com/NativePHP/laravel/pull/610
> Add emoji panel API endpoints for support check and display

- resources/js/electron-plugin/dist/server/api/window.js
- resources/js/electron-plugin/src/server/api/window.ts
Required Electron changes for PR https://github.com/NativePHP/laravel/pull/686 (see details there).
> Add possibility to prevent navigation away from current domain or page
